### ISSUE TITLE
Demo app not working

### ISSUE THREAD

**Issue by IG-Stanimir-Dimitrov** [IgniteUI/ERDashboard-Angular#3]
The demo application is not working.

`Error loading https://unpkg.com/@angular/common/bundles/common.umd.js as "@angular/common" from https://unpkg.com/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js`

**Comment by dkamburov** [comment]
Closing with the following commit https://github.com/IgniteUI/ERDashboard-Angular/commit/230167dc00f80ec55d9ef981e14b5497fd610475
